on: [push]

jobs:
  optix_plugin_job:
    runs-on: ubuntu-latest
    name: test job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          operation: "scan"
          APIKey: "b471f931-f2f2-43d1-a535-6ea160a8ff17"
          files: "file"
          repo_url: "branch"
          branch: "branhc"
          committer_name: "committer_name"
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The status ${{ steps.hello.outputs.response_status }} with data ${{ steps.hello.outputs.response_data }}"
